name: 'WorldBorder'
version: '${version}'
description: 'Configure a border for each world so players can not go beyond that.'
main: 'me.sagirii.worldborder.WorldBorderPlugin'
api-version: '1.20'

commands:
  border:
    description: World Border's main command.
    usage: /<command> <subcommand>